# This file is auto-generated by core/scripts/generate-python-exchanges.js
# Do not edit manually.
# To regenerate: npm run generate:sdk:all --workspace=pmxt-core
# Source of truth: core/src/server/app.ts (createExchange function)

from typing import Any, Dict, Optional

from .client import Exchange

class Polymarket(Exchange):
    """Polymarket exchange client."""

    def __init__(
        self,
        api_key: Optional[str] = None,
        api_secret: Optional[str] = None,
        passphrase: Optional[str] = None,
        private_key: Optional[str] = None,
        proxy_address: Optional[str] = None,
        signature_type: Optional[Any] = "gnosis-safe",
        base_url: str = "http://localhost:3847",
        auto_start_server: bool = True,
    ):
        """
        Initialize Polymarket client.

        Args:
            api_key: API key for authentication (optional)
            api_secret: API secret for authentication (optional)
            passphrase: Passphrase for authentication (optional)
            private_key: Private key for authentication (optional)
            proxy_address: Proxy/smart wallet address (optional)
            signature_type: Signature type (optional)
            base_url: Base URL of the PMXT sidecar server
            auto_start_server: Automatically start server if not running (default: True)
        """
        super().__init__(
            exchange_name="polymarket",
            api_key=api_key,
            private_key=private_key,
            proxy_address=proxy_address,
            signature_type=signature_type,
            base_url=base_url,
            auto_start_server=auto_start_server,
        )

        self.api_secret = api_secret
        self.passphrase = passphrase

    def _get_credentials_dict(self) -> Optional[Dict[str, Any]]:
        creds = super()._get_credentials_dict() or {}
        if self.api_secret:
            creds["apiSecret"] = self.api_secret
        if self.passphrase:
            creds["passphrase"] = self.passphrase
        return creds if creds else None


class Limitless(Exchange):
    """Limitless exchange client."""

    def __init__(
        self,
        api_key: Optional[str] = None,
        api_secret: Optional[str] = None,
        passphrase: Optional[str] = None,
        private_key: Optional[str] = None,
        base_url: str = "http://localhost:3847",
        auto_start_server: bool = True,
    ):
        """
        Initialize Limitless client.

        Args:
            api_key: API key for authentication (optional)
            api_secret: API secret for authentication (optional)
            passphrase: Passphrase for authentication (optional)
            private_key: Private key for authentication (optional)
            base_url: Base URL of the PMXT sidecar server
            auto_start_server: Automatically start server if not running (default: True)
        """
        super().__init__(
            exchange_name="limitless",
            api_key=api_key,
            private_key=private_key,
            base_url=base_url,
            auto_start_server=auto_start_server,
        )

        self.api_secret = api_secret
        self.passphrase = passphrase

    def _get_credentials_dict(self) -> Optional[Dict[str, Any]]:
        creds = super()._get_credentials_dict() or {}
        if self.api_secret:
            creds["apiSecret"] = self.api_secret
        if self.passphrase:
            creds["passphrase"] = self.passphrase
        return creds if creds else None


class Kalshi(Exchange):
    """Kalshi exchange client."""

    def __init__(
        self,
        api_key: Optional[str] = None,
        private_key: Optional[str] = None,
        base_url: str = "http://localhost:3847",
        auto_start_server: bool = True,
    ):
        """
        Initialize Kalshi client.

        Args:
            api_key: API key for authentication (optional)
            private_key: Private key for authentication (optional)
            base_url: Base URL of the PMXT sidecar server
            auto_start_server: Automatically start server if not running (default: True)
        """
        super().__init__(
            exchange_name="kalshi",
            api_key=api_key,
            private_key=private_key,
            base_url=base_url,
            auto_start_server=auto_start_server,
        )


class KalshiDemo(Exchange):
    """KalshiDemo exchange client."""

    def __init__(
        self,
        api_key: Optional[str] = None,
        private_key: Optional[str] = None,
        base_url: str = "http://localhost:3847",
        auto_start_server: bool = True,
    ):
        """
        Initialize KalshiDemo client.

        Args:
            api_key: API key for authentication (optional)
            private_key: Private key for authentication (optional)
            base_url: Base URL of the PMXT sidecar server
            auto_start_server: Automatically start server if not running (default: True)
        """
        super().__init__(
            exchange_name="kalshi-demo",
            api_key=api_key,
            private_key=private_key,
            base_url=base_url,
            auto_start_server=auto_start_server,
        )


class Probable(Exchange):
    """Probable exchange client."""

    def __init__(
        self,
        api_key: Optional[str] = None,
        api_secret: Optional[str] = None,
        passphrase: Optional[str] = None,
        private_key: Optional[str] = None,
        base_url: str = "http://localhost:3847",
        auto_start_server: bool = True,
    ):
        """
        Initialize Probable client.

        Args:
            api_key: API key for authentication (optional)
            api_secret: API secret for authentication (optional)
            passphrase: Passphrase for authentication (optional)
            private_key: Private key for authentication (optional)
            base_url: Base URL of the PMXT sidecar server
            auto_start_server: Automatically start server if not running (default: True)
        """
        super().__init__(
            exchange_name="probable",
            api_key=api_key,
            private_key=private_key,
            base_url=base_url,
            auto_start_server=auto_start_server,
        )

        self.api_secret = api_secret
        self.passphrase = passphrase

    def _get_credentials_dict(self) -> Optional[Dict[str, Any]]:
        creds = super()._get_credentials_dict() or {}
        if self.api_secret:
            creds["apiSecret"] = self.api_secret
        if self.passphrase:
            creds["passphrase"] = self.passphrase
        return creds if creds else None


class Baozi(Exchange):
    """Baozi exchange client."""

    def __init__(
        self,
        private_key: Optional[str] = None,
        base_url: str = "http://localhost:3847",
        auto_start_server: bool = True,
    ):
        """
        Initialize Baozi client.

        Args:
            private_key: Private key for authentication (optional)
            base_url: Base URL of the PMXT sidecar server
            auto_start_server: Automatically start server if not running (default: True)
        """
        super().__init__(
            exchange_name="baozi",
            private_key=private_key,
            base_url=base_url,
            auto_start_server=auto_start_server,
        )


class Myriad(Exchange):
    """Myriad exchange client."""

    def __init__(
        self,
        api_key: Optional[str] = None,
        wallet_address: Optional[str] = None,
        base_url: str = "http://localhost:3847",
        auto_start_server: bool = True,
    ):
        """
        Initialize Myriad client.

        Args:
            api_key: API key for authentication (optional)
            wallet_address: Wallet address (required for positions and balance)
            base_url: Base URL of the PMXT sidecar server
            auto_start_server: Automatically start server if not running (default: True)
        """
        super().__init__(
            exchange_name="myriad",
            api_key=api_key,
            private_key=wallet_address,
            base_url=base_url,
            auto_start_server=auto_start_server,
        )
